graph TD
    Opp0["Organic Agriculture Aid Scheme..."]
    class Opp0 Opportunity
    Doc_bio_2019_pdf["bio_2019_pdf"]
    Opp0 -->|definedBy| Doc_bio_2019_pdf
    Opp1["Organic Agriculture Aid Scheme..."]
    class Opp1 Opportunity
    Doc_bio_2019_pdf["bio_2019_pdf"]
    Opp1 -->|definedBy| Doc_bio_2019_pdf
    Opp2["Allowance for areas subject to..."]
    class Opp2 Opportunity
    Doc_izcns2019_pdf["izcns2019_pdf"]
    Opp2 -->|definedBy| Doc_izcns2019_pdf
    Opp3["Transitional aid for former na..."]
    class Opp3 Opportunity
    Doc_izcns2019_pdf["izcns2019_pdf"]
    Opp3 -->|definedBy| Doc_izcns2019_pdf
    Opp4["MB1.a Hedges and wooded strips..."]
    class Opp4 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp4 -->|definedBy| Doc_maec2019_pdf
    Opp5["MB1.b Isolated trees, shrubs, ..."]
    class Opp5 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp5 -->|definedBy| Doc_maec2019_pdf
    Opp6["MB11.c Threatened local breed:..."]
    class Opp6 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp6 -->|definedBy| Doc_maec2019_pdf
    Opp7["MC3 Floodable meadow..."]
    class Opp7 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp7 -->|definedBy| Doc_maec2019_pdf
    Opp8["MC4 High biological value mead..."]
    class Opp8 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp8 -->|definedBy| Doc_maec2019_pdf
    Opp9["MC7 Developed plot..."]
    class Opp9 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp9 -->|definedBy| Doc_maec2019_pdf
    Opp10["MC8 Developed strip..."]
    class Opp10 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp10 -->|definedBy| Doc_maec2019_pdf
    Opp11["MC10 Agro-environmental action..."]
    class Opp11 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp11 -->|definedBy| Doc_maec2019_pdf
    Opp12["MB1.c Ponds..."]
    class Opp12 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp12 -->|definedBy| Doc_maec2019_pdf
    Opp13["MB2 Natural meadow..."]
    class Opp13 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp13 -->|definedBy| Doc_maec2019_pdf
    Opp14["MB5 Herbaceous headland..."]
    class Opp14 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp14 -->|definedBy| Doc_maec2019_pdf
    Opp15["MB6 Environmentally friendly c..."]
    class Opp15 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp15 -->|definedBy| Doc_maec2019_pdf
    Opp16["MB9.a Forage autonomy 1.4 UGB/..."]
    class Opp16 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp16 -->|definedBy| Doc_maec2019_pdf
    Opp17["MB9.b Forage autonomy 1.8 UGB/..."]
    class Opp17 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp17 -->|definedBy| Doc_maec2019_pdf
    Opp18["MB11.a Threatened local breed:..."]
    class Opp18 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp18 -->|definedBy| Doc_maec2019_pdf
    Opp19["MB11.b Threatened local breed:..."]
    class Opp19 Opportunity
    Doc_maec2019_pdf["maec2019_pdf"]
    Opp19 -->|definedBy| Doc_maec2019_pdf